LeaderStats/Models/ViewModels/CompanyViewModel.cs
using System.Collections.Generic;

namespace LeaderStats.Models.ViewModels
{
    public class CompanyViewModel
    {
        public string Name { get; set; }
        public string Ticker { get; set; }
        public List<Leader> Employees { get; set; }
    }
}

LeaderStats/Controllers/CompanyController.cs
using System.Linq;
using System.Web.Mvc;
using LeaderStats.Models.ViewModels;

namespace LeaderStats.Controllers
{
    public class CompanyController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Search(string term)
        {
            if(!Models.Indexes.CompanyIndex.Index.ContainsKey(term.ToLower()))
            {
                return View(new CompanyViewModel());
            }

            var company = Models.Indexes.CompanyIndex.Index[term.ToLower()];
            var viewModel = new CompanyViewModel
                                {
                                    Name = company.First().Company,
                                    Ticker = company.First().Ticker,
                                    Employees = company
                                };
            return View(viewModel);
        }

        public JsonResult CompanyAutoComplete(string searchTerm, int count)
        {
            var keys = Models.Indexes.CompanyIndex.Index.Keys;
            var results = keys.Where(key => key.ToLower().StartsWith(searchTerm.ToLower())).ToList();

            if (count == 0)
                count = results.Count;

            return Json(results.Take(count), JsonRequestBehavior.AllowGet);
        }

    }
}

LeaderStats/Views/Company/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/layouts/default.cshtml";
}

<h2>Index</h2>


    @using(Html.BeginForm("Search", "Company"))
    {
        
       @Html.TextBox("term", String.Empty, new { id="keywords" })
        <input type="submit" value="Search" />
    }



LeaderStats/Views/Company/Search.cshtml
@model LeaderStats.Models.ViewModels.CompanyViewModel
           
@{
    ViewBag.Title = "Search Result";
    Layout = "~/Views/Shared/layouts/default.cshtml";
}

<h2>Search Result</h2>

@if (String.IsNullOrEmpty(Model.Name))
{
<p style="color:Red">Company could not be found.</p>
}
else
{
<h3 style="color:White"> Name : @Model.Name</h3><br />
<h3 style="color:White"> Ticker : @Model.Ticker</h3><br /> 
<h3 style="color:White"> Employees count : @Model.Employees.Count</h3><br />
    foreach (var employee in @Model.Employees)
    {
        @Html.Partial("~/Views/Leader/_Leader.cshtml", employee)
    }
  }